export const WISH_TYPES_RECEIVE_SUCCESS = 'WISH_TYPES_RECEIVE_SUCCESS';
export const WISH_TYPES_RECEIVE_FAILURE = 'WISH_TYPES_RECEIVE_FAILURE';

export const WISH_TYPE_CREATE_SUCCESS = 'WISH_TYPE_CREATE_SUCCESS';
export const WISH_TYPE_CREATE_FAILURE = 'WISH_TYPE_CREATE_FAILURE';

export const WISH_TYPE_UPDATE_SUCCESS = 'WISH_TYPE_UPDATE_SUCCESS';
export const WISH_TYPE_UPDATE_FAILURE = 'WISH_TYPE_UPDATE_FAILURE';

export const WISH_TYPE_DELETE_SUCCESS = 'WISH_TYPE_DELETE_SUCCESS';
export const WISH_TYPE_DELETE_FAILURE = 'WISH_TYPE_DELETE_FAILURE';

