export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const WISH_ORDER_SUCCESS = 'WISH_ORDER_SUCCESS';
export const WISH_TYPES_RECEIVED = 'WISH_TYPES_RECEIVED';
export const WISH_CHECKED = 'WISH_CHECKED';
export const WISH_ORDER_FIELD_CHANGED = 'WISH_ORDER_FIELD_CHANGED';
export const WISH_ORDER_VALIDATION_FAILED = 'WISH_ORDER_VALIDATION_FAILED';