export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_IN_ADMIN_SUCCESS = 'LOG_IN_ADMIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

export const WISH_ORDER_SUCCESS = 'WISH_ORDER_SUCCESS';
export const WISH_ORDER_FAILED = 'WISH_ORDER_FAILED';
export const WISH_CHECKED = 'WISH_CHECKED';
export const WISH_ORDER_FIELD_CHANGED = 'WISH_ORDER_FIELD_CHANGED';
export const WISH_ORDER_VALIDATION_FAILED = 'WISH_ORDER_VALIDATION_FAILED';

export const WISH_TYPES_RECEIVED = 'WISH_TYPES_RECEIVED';
export const WISH_CATEGORIES_RECEIVED = 'WISH_CATEGORIES_RECEIVED';
export const WISH_ORDERS_RECEIVED = 'WISH_ORDERS_RECEIVED';

export const WISH_CATEGORY_WAS_DELETED = 'WISH_CATEGORY_WAS_DELETED';
export const WISH_TYPE_WAS_DELETED = 'WISH_TYPE_WAS_DELETED';
